---
title: "Class3_Vectors"
format: html
editor: visual
---

## Vectors, Matrices, R exercises-basic

```{r}
prob1_a <- 1:20
prob1_a

prob1_b <- 20:1
prob1_b

prob1_c <- c(1:20, 19:1)
prob1_c

temp <- c(4, 6, 3)
temp

prob1_e <- rep(temp, times = 10)
prob1_e

prob1_f <- rep(temp, length.out=31)
prob1_f

prob1_g <- c(rep(4, times = 10), rep(6, times = 20), rep(3, times = 30))
prob1_g
```

```{r}
# prob2
x_values <- seq(3, 6, by = 0.1)
vector_2 <- exp(x_values) * cos(x_values)
vector_2
```

```{r}
#prob3_a
first_exponents <- seq(3, 36, by = 3)
second_exponents <- seq(1, 34, by = 3)
prob3_a <- (0.1^first_exponents) * (0.2^second_exponents)
prob3_a
```

```{r}
#prob3_b

prob4 <- sapply(2:25, function(x) (2^x)/x)
prob4

```

```{r}
#prob5_a
prob5_a <- paste("label", 1:30)
prob5_a

```

```{r}
#prob5_b
prob5_b <- paste0("fn", 1:30)
prob5_b
```

```{r}
#prob6
set.seed(50)
xVec <- sample(0:999, 250, replace=T)
yVec <- sample(0:999, 250, replace=T)

prob6_a <- yVec[2:250] - xVec[1:249]
prob6_a

prob6_b <- sin(yVec[1:249])/cos(xVec[2:250])
prob6_b

prob6_c <- xVec[1:248] + 2*xVec[2:249] - xVec[3:250]
prob6_c

prob6_d <- sum((exp(-xVec[2:249]))/(xVec[1:249]+10))
prob6_d
```

```{r}
#prob7

prob7_a <- yVec[yVec > 600]
prob7_a

prob7_b <- which(yVec > 600)
prob7_b

prob7_c <- xVec[prob7_b]
prob7_c

#prob7_d 
x_mean <- mean(xVec)
prob7_d <- abs(xVec - x_mean)^(1/2)
prob7_d

#prob7_e
max_yVec <- max(yVec)
prob7_e <- sum(yVec >= (max_yVec - 200))
prob7_e

#prob7_f
prob7_f <- sum(xVec %% 2 == 0)
prob7_f

#prob7_g
prob7_g <- xVec[order(yVec)]
prob7_g

#prob7_h
indices <- seq(1, length(yVec), by = 3)
prob7_h <- yVec[indices]
prob7_h

```

```{r}
#prob8
fraction_series <- (2 * seq(4, 38, by = 2)) / (seq(3, 39, by = 2))
prob8 <- 1 + sum(cumprod(fraction_series))
prob8
```
